name: Approval Required for Deletion

on:
  push:
    branches:
      - "*"
    paths:
      - ".github/workflows/**/*.yml"
      - ".github/workflows/**/*.yaml"
  pull_request:
    branches:
      - "*"
    paths:
      - ".github/workflows/**/*.yml"
      - ".github/workflows/**/*.yaml"

jobs:
  check_approval:
    runs-on: ubuntu-latest
    steps:
      - name: Check Approvals
        run: echo "HI"
