name: 'Deploy Load Balancer - main'
run-name: 'Load Balancer - ${{inputs.environment}} : ${{inputs.requesttype}}'
on:
  workflow_dispatch:
    inputs:
      requesttype:
        type: choice
        required: true
        description: Request Type
        options:
            - Create Main Deploy (with New RG)
            - Create Main Deploy (with Existing RG)
            - Remove
        default: "Create Main Deploy (with New RG)"
      environment:
        type: choice
        required: true
        description: Environment
        options:
          - dev
          - prod

jobs:

  load_balancer_main_deploy_new_rg:
    if: (github.event.inputs.requesttype == 'Create Main Deploy (with New RG)')
    name: 'Load Balancer'
    uses: ./.github/workflows/called_from_deploy.yml
    secrets: inherit
    with:
      requesttype:                 '${{inputs.requesttype}}'
      environment:                 '${{inputs.environment}}'
  
  load_balancer_main_deploy_existing_rg:
    if: (github.event.inputs.requesttype == 'Create Main Deploy (with Existing RG)')
    name: 'Load Balancer '
    uses: ./.github/workflows/called_from_deploy.yml
    secrets: inherit
    with:
      requesttype:                 '${{inputs.requesttype}}'
      environment:                 '${{inputs.environment}}'

  load_balancer_main_deploy_remove:
    if: (github.event.inputs.requesttype == 'Remove')
    name: 'Load Balancer '
    uses: ./.github/workflows/called_from_deploy.yml
    secrets: inherit
    with:
      requesttype:                 '${{inputs.requesttype}}'
      environment:                 '${{ inputs.environment == ''dev'' && ''dev_handle_removal'' || inputs.environment }}'